version: '3.4'

services:
  api:
    image: api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type != tiebreaker]
    ports:
      - "8070:80"
    networks:
      - web

  app_web:
    image: app_web
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type != tiebreaker]
    ports:
      - "8075:8502"
    networks:
      - web

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - web

networks:
  web:

volumes:
  mongodb_data:
    driver: local
