version: '3.4'

services:
  api:
    image: api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type != tiebreaker]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.middlewares=api_stripprefix,api_compress"
        - "traefik.http.middlewares.api_stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.api_compress.compress=true"
        - "traefik.http.services.api.loadbalancer.server.port=80"
    ports:
      - "8070:80"
    networks:
      - web

  app_web:
    image: app_web
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type != tiebreaker]
    ports:
      - "8075:8502"
    networks:
      - web

networks:
  web:

